### ISSUE TITLE
Suggestion: support for tool-specific extensions

### ISSUE THREAD

**Issue by simonw** [modelyaml/modelyaml#1]
This is a really interesting proposal!

I've been wanting something like this for my own [LLM](https://llm.datasette.io/) project - a file format which can be used to tell my software how to run a completely new model.

I was actually sketching out something similar to `model.yaml` based around YAML embedded in frontmatter of a Markdown file - my idea was to call it a "model card" and have it be a Markdown file that describes the model and contains YAML configuration that looks very much like what `model.yaml` is doing here.

A feature I'd love to see in `model.yaml` is some kind of support for tool-specific extensions. In the case of my LLM Python tool everything revolves around plugins, so I'd like to be able to add something like this:

```yaml
model: mistral-small-3.2-24b-instruct-2506
base:
  - key: lmstudio-community/mistral-small-3.2-24b-instruct-2506-gguf
    sources:
      - type: huggingface
        user: lmstudio-community
        repo: Mistral-Small-3.2-24B-Instruct-2506-GGUF
# ...
platforms:
  python-llm:
    plugin: llm-gguf
```
In this case this is saying that the `python-llm` tool (I figure just `llm` would look a little confusing here) needs to install the [llm-gguf](https://pypi.org/project/llm-gguf/) plugin in order to run this model.

In my case I also want to be able to support models that are hosted elsewhere, so I'd want to have some `model.yaml` files that look more like this:
```yaml
model: claude-3.5-sonnet
# ...
platforms:
  python-llm:
    plugin: llm-anthropic>=0.17
    model_id: claude-3.5-sonnet
```
This is saying "use the `llm-anthropic>=0.17` plugin and configure it with this `model_id`".
